---

- name: Create user if not already exists - {{ bash_alias_for }}
  ansible.builtin.user:
    name: "{{ bash_alias_for }}"
    shell: /bin/bash
    state: present
  tags: [pgcenter_alias, pgcenter]

- name: Add bash alias to profile - {{ bash_alias_path }}
  ansible.builtin.lineinfile:
    path: "{{ bash_alias_path }}"
    create: true
    owner: "{{ bash_alias_for }}"
    group: "{{ bash_alias_for }}"
    mode: "0644"
    line: "{{ bash_alias }}"
    regexp: "^{{ bash_alias }}"
  tags: [pgcenter_alias, pgcenter]
