---

- name: check user "{{ bash_alias_for }}" | create user if not already exist
  user:
    name: "{{ bash_alias_for }}"
    shell: /bin/bash
    state: present
  tags: [ pgcenter_alias, pgcenter ]

- name: add "{{ bash_alias }}" to "{{ bash_alias_path }}"
  lineinfile:
    path: "{{ bash_alias_path }}"
    create: yes
    owner: "{{ bash_alias_for }}"
    group: "{{ bash_alias_for }}"
    mode: 0644
    line: "{{ bash_alias }}"
    regexp: "^{{ bash_alias }}"
  tags: [ pgcenter_alias, pgcenter ]
