---
# tasks file for ansible-role-pgcenter

- name: Install pgcenter
  ansible.builtin.import_tasks: pgcenter.yml
  tags: pgcenter

- name: Configure pgcenter bash alias
  ansible.builtin.import_tasks: bash_alias.yml
  when: set_pgcenter_alias | bool
  tags: pgcenter_alias
