---

- name: download and extract "pgcenter_{{ pgcenter_version }}_linux_amd64.tar.gz" into /tmp
  ansible.builtin.unarchive:
    src: "https://github.com/lesovsky/pgcenter/releases/download/v{{ pgcenter_version }}/pgcenter_{{ pgcenter_version }}_linux_amd64.tar.gz"
    dest: /tmp/
    remote_src: true
    validate_certs: true
  environment: '{{ proxy_env | default({}) }}'
  tags: [ pgcenter_get, pgcenter ]

- name: copy "pgcenter" binary file to "/usr/local/bin/"
  ansible.builtin.copy:
    src: /tmp/pgcenter
    dest: /usr/local/bin/
    mode: "0755"
    remote_src: true
  tags: [ pgcenter_install, pgcenter ]
